### ISSUE TITLE
Internal Server Error after /oidc/callback/

### ISSUE THREAD

**Issue by Rintsi** [fedora-iot/zezere#99]
Running on localhost with
```
docker run --name zezere \
    -e OIDC_RP_CLIENT_ID=<client id> \
    -e OIDC_RP_CLIENT_SECRET=<client secret> \
    -e OIDC_OP_AUTHORIZATION_ENDPOINT=<authorization endpoint> \
    -e OIDC_OP_TOKEN_ENDPOINT=<token endpoint> \
    -e OIDC_OP_USERINFO_ENDPOINT=<userinfo endpoint> \
    -e OIDC_OP_JWKS_ENDPOINT=<jwks endpoint> \
    -e AUTH_METHOD=oidc \
    -e SECRET_KEY=<secret key> \
    -e ALLOWED_HOSTS=localhost \
    --detach --rm \
    -p 8080:8080 \
    -t quay.io/fedora-iot/zezere:latest
```

After successful authentication the /oidc/callback/ throws 500:

```
172.17.0.1 - - [10/Dec/2020:19:03:35 +0000] "GET /accounts/login/?next=/portal/ HTTP/1.1" 302 -
172.17.0.1 - - [10/Dec/2020:19:03:35 +0000] "GET /oidc/authenticate/ HTTP/1.1" 302 -
[Thu Dec 10 19:03:42.653278 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814] Internal Server Error: /oidc/callback/
[Thu Dec 10 19:03:42.653306 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814] Traceback (most recent call last):
[Thu Dec 10 19:03:42.653310 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Dec 10 19:03:42.653313 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     response = get_response(request)
[Thu Dec 10 19:03:42.653316 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
[Thu Dec 10 19:03:42.653320 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Dec 10 19:03:42.653323 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
[Thu Dec 10 19:03:42.653327 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     return self.dispatch(request, *args, **kwargs)
[Thu Dec 10 19:03:42.653330 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
[Thu Dec 10 19:03:42.653334 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     return handler(request, *args, **kwargs)
[Thu Dec 10 19:03:42.653337 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/mozilla_django_oidc/views.py", line 99, in get
[Thu Dec 10 19:03:42.653342 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     self.user = auth.authenticate(**kwargs)
[Thu Dec 10 19:03:42.653345 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
[Thu Dec 10 19:03:42.653350 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     user = backend.authenticate(request, **credentials)
[Thu Dec 10 19:03:42.653354 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 286, in authenticate
[Thu Dec 10 19:03:42.653359 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     return self.get_or_create_user(access_token, id_token, payload)
[Thu Dec 10 19:03:42.653363 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 307, in get_or_create_user
[Thu Dec 10 19:03:42.653367 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     user_info = self.get_userinfo(access_token, id_token, payload)
[Thu Dec 10 19:03:42.653371 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 243, in get_userinfo
[Thu Dec 10 19:03:42.653376 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     proxies=self.get_settings('OIDC_PROXY', None))
[Thu Dec 10 19:03:42.653380 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 76, in get
[Thu Dec 10 19:03:42.653384 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     return request('get', url, params=params, **kwargs)
[Thu Dec 10 19:03:42.653389 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 61, in request
[Thu Dec 10 19:03:42.653394 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     return session.request(method=method, url=url, **kwargs)
[Thu Dec 10 19:03:42.653398 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 528, in request
[Thu Dec 10 19:03:42.653402 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     prep = self.prepare_request(req)
[Thu Dec 10 19:03:42.653406 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 466, in prepare_request
[Thu Dec 10 19:03:42.653410 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     hooks=merge_hooks(request.hooks, self.hooks),
[Thu Dec 10 19:03:42.653414 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 316, in prepare
[Thu Dec 10 19:03:42.653417 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     self.prepare_url(url, params)
[Thu Dec 10 19:03:42.653422 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]   File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 390, in prepare_url
[Thu Dec 10 19:03:42.653427 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814]     raise MissingSchema(error)
[Thu Dec 10 19:03:42.653431 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814] requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
[Thu Dec 10 19:03:42.653441 2020] [wsgi:error] [pid 21:tid 139663898695424] [remote 172.17.0.1:53814] 
172.17.0.1 - - [10/Dec/2020:19:03:42 +0000] "GET /oidc/callback/?code=<code>&state=<state> HTTP/1.1" 500 145
```

**Comment by Rintsi** [comment]
As per usual how the things unfold. I had a wrong environment variable name. OIDC_OP_USERINFO_ENDPOINT should be OIDC_OP_USER_ENDPOINT instead.
